routes/web.php
<?php



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/welcome', function () {
//     return view('welcome');
// });


// Auth::routes();
Auth::routes([
    'verify' => true,
    'register' => false,
    ]);

Route::resource('/', 'RequestController');
Route::resource('request', 'RequestController');

Route::resource('shares', 'ShareController');



// Route::resource('requests', 'SupportRequestController');
// Route::get('requests', 'SupportRequestController@getGuzzleRequest');


Route::resource('welcome', 'ShareController@getGuzzleRequest');

//Add clients
Route::resource('client', 'ClientController');
//manage users
Route::resource('manage_users', 'UserManagerController');
///
Route::resource('books', 'BookController');
//Man Hours
Route::resource('man_hours',  'ManhourController');

//change passsword routes
Route::get('change-password', 'ChangePasswordController@index');
Route::post('change-password', 'ChangePasswordController@store')->name('change.password');

resources/views/manage_users/create.blade.php
@extends('layouts.master')
@section('content')
<main id="main-container">
    <div class="content">


        <div class="row">
            <div class="col-md-12 col-lg-6">

                <!-- Form row -->
                <div class="card">
                    <div class="card-header">Create New User</div>
                    <div class="card-body">

                        <!--
						The .form-group class is the easiest way to add some structure to forms. Its only purpose is to provide margin-bottom around a label and control pairing. As a bonus, since it's a class you can use it with <fieldset>s, <div>s, or nearly any other element.
						You may also swap .row for .form-row, a variation of our standard grid row that overrides the default column gutters for tighter and more compact layouts.
						-->
                        <form method="post" action="{{ route('manage_users.store') }}">
                            @csrf

                            <div class="form-group">
                                <label for="inputAddress2" class="col-form-label">Name</label>
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>
                                @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="inputAddress" class="col-form-label">Email</label>
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">
                                @error('email')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <input id="password" type="password" hidden value="Tamarix2020" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">

                                @error('password')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <!-- <label for="inputAddress2" class="col-form-label">PasswordConfirmation</label> -->
                                <input id="password-confirm" hidden value="Tamarix2020" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
                            </div>


                            <div class="form-group">
                                <!-- <label for="inputAddress2" class="col-form-label">status</label> -->
                                <!-- <input type="text" value="0" hidden value="Tamarix@2030" readonly class="form-control" hidden id="inputAddress2" name="status" placeholder="Apartment, studio, or floor"> -->
                            </div>
                            <button type="submit" class="btn btn-primary">Create User</button>
                        </form>

                    </div><!-- .card-body -->
                </div><!-- .card -->
                <!-- /End Form row -->

            </div><!-- .col -->


        </div><!-- .row -->



        @include('sweetalert::alert')
    </div><!-- .content -->
</main>
@stop

resources/views/manage_users/index.blade.php
@extends('layouts.master')
@section('content')
<main id="main-container">
    <div class="content">

        @auth
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6">

                <!-- Item sold -->
                <div class="card stats-card">
                    <div class="stats-icon bg-success">
                        <span class="ti-user"></span>
                    </div>
                    <div class="stats-ctn">
                        <div class="stats-counter"><span class="counter">{{$count_users}}</span></div>
                        <span class="desc">Total Users</span>
                    </div>
                </div><!-- .card -->
                <!-- /End Item sold -->

            </div><!-- .col -->
            <div class="col-lg-3 col-md-6 col-sm-6">

                <!-- Earnings -->
                <div class="card stats-card">
                    <div class="stats-icon bg-danger">
                        <span class="ti-user"></span>
                    </div>
                    <div class="stats-ctn">
                        <div class="stats-counter"><span class="counter">Coming Soon</span></div>
                        <span class="desc">Total Admins</span>
                    </div>
                </div><!-- .card -->
                <!-- /End Earnings -->

            </div><!-- .col -->
            <div class="col-lg-3 col-md-6 col-sm-6">

                <!-- Messages -->
                <div class="card stats-card">
                    <div class="stats-icon bg-info">
                        <span class="ti-user"></span>
                    </div>
                    <div class="stats-ctn">
                        <div class="stats-counter"><span class="counter">coming soon </span></div>
                        <span class="desc">Active Users</span>
                    </div>
                </div><!-- .card -->
                <!-- /End Messages -->

            </div><!-- .col -->
            <div class="col-lg-3 col-md-6 col-sm-6">

                <!-- Notifications -->
                <div class="card stats-card">
                    <div class="stats-icon bg-secondary">
                        <span class="ti-user"></span>
                    </div>
                    <div class="stats-ctn">
                        <div class="stats-counter"><span class="counter">Coming Soon</span></div>
                        <span class="desc">InActive Users</span>
                    </div>
                </div><!-- .card -->
                <!-- /End Notifications -->

            </div><!-- .col -->
        </div><!-- .row -->
        <div class="row">
            <div class="col-12">

                <!-- Invoice -->
                <div class="card">
                    <div class="card-body">
                        <div class="card-header-inside">
                            Service Tickets
                        </div>

                        <table id="mytable" class="table table-striped table-responsive">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Role</th>
                                    <th>User Since</th>
                                </tr>
                            </thead>
                            <tbody>



                                @foreach($users as $client)
                                <tr>
                                    <td>{{ $client->name }}</td>
                                    <td>{{ $client->email }}</td>
                                    <td>{{ $client->email }}</td>
                                    <td>{{ \Carbon\Carbon::parse($client->created_at)->format('d/M/Y')}}</td>
                                </tr>
                                @endforeach


                            </tbody>
                        </table>

                    </div><!-- .card-body -->
                </div><!-- .card -->
                <!-- /End Invoice -->


            </div><!-- .col -->
        </div><!-- .row -->
        @else

        @endauth


        @include('sweetalert::alert')
    </div><!-- .content -->
</main>
@stop