routes/web.php
<?php



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/welcome', function () {
//     return view('welcome');
// });


// Auth::routes();
Auth::routes([
    'verify' => true,
    'register' => false,
    ]);

Route::resource('/', 'RequestController');
Route::resource('request', 'RequestController');

Route::resource('shares', 'ShareController');



// Route::resource('requests', 'SupportRequestController');
// Route::get('requests', 'SupportRequestController@getGuzzleRequest');


Route::resource('welcome', 'ShareController@getGuzzleRequest');

//Add clients
Route::resource('client', 'ClientController');
//manage users
Route::resource('manage_users', 'UserManagerController');
///
Route::resource('books', 'BookController');
//Man Hours
Route::resource('man_hours',  'ManhourController');

//change passsword routes
Route::get('change-password', 'ChangePasswordController@index');
Route::post('change-password', 'ChangePasswordController@store')->name('change.password');

app/Http/Controllers/RequestController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Mail\RequestReceived;
use App\Mail\SendNotification;
use App\Share;
use RealRashid\SweetAlert\Facades\Alert;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Mail;
use App\Mail\TicketRespond;
use Dotenv\Loader;
use App\Client;
use App\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Input;


class RequestController extends Controller
{
    //
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    // public function __construct()
    // {
    //     $this->middleware(['auth', 'verified']);
    // }
    public function index()
    {
        if (session('success_message')) {
            Alert::success('Thank you', session('success_message'));
        }
        $requests = Share::orderBy('status')->get();
        $group_mail = DB::table('users')->orderByDesc('id');
        $count_resolved = Share::where('status', 1)->count();    //1 resolved 0 not resolved
        $count_notresolved = Share::where('status', 0)->count();
        $count_new = Share::whereDate('created_at', Carbon::today())->where('status', 0)->count();
        $new_tickets = Share::whereDate('created_at', Carbon::today())->where('status', 0)->get();
        $count_total = Share::all()->count();
        $project = Client::all();
        return view('request.create', compact('requests', 'group_mail', 'count_resolved', 'count_notresolved', 'count_new', 'count_total', 'new_tickets', 'project'));
        // if (session('success_message')) {
        //     Alert::success('Thank you', session('success_message'));
        // }
        // $requests = Share::orderBy('status')->get();
        // $group_mail = DB::table('users')->orderByDesc('id');
        // $count_resolved = Share::where('status', 1)->count();    //1 resolved 0 not resolved
        // $count_notresolved = Share::where('status', 0)->count();
        // $count_new = Share::whereDate('created_at', Carbon::today())->where('status', 0)->count();
        // $new_tickets = Share::whereDate('created_at', Carbon::today())->where('status', 0)->get();
        // $count_total = Share::all()->count();
        // $project = Client::all();
        // return view('request.index', compact('requests', 'group_mail', 'count_resolved', 'count_notresolved', 'count_new', 'count_total', 'new_tickets', 'project'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        if (session('success_message')) {
            Alert::success('Thank you', session('success_message'));
        }
        $requests = Share::orderBy('status')->get();
        $group_mail = DB::table('users')->orderByDesc('id');
        $count_resolved = Share::where('status', 1)->count();    //1 resolved 0 not resolved
        $count_notresolved = Share::where('status', 0)->count();
        $count_new = Share::whereDate('created_at', Carbon::today())->where('status', 0)->count();
        $new_tickets = Share::whereDate('created_at', Carbon::today())->where('status', 0)->get();
        $count_total = Share::all()->count();
        $project = Client::all();
        return view('request.create', compact('requests', 'group_mail', 'count_resolved', 'count_notresolved', 'count_new', 'count_total', 'new_tickets', 'project'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'support_ticket_no' => 'required',
            'contact_email' => 'required',
            'company' => 'required',
            'application' => 'required',
            'priority' => 'required',
            'status' => 'required|integer',
            'bookcover' => 'image|max:5120'
        ]);
        $cover = $request->file('bookcover');
        if (!empty($cover)) {
            $extension = $cover->getClientOriginalExtension();
            Storage::disk('public')->put($cover->getFilename() . '.' . $extension,  File::get($cover));
            $share = new Share();
            $share->support_ticket_no = $request->support_ticket_no;
            $share->contact_email = $request->contact_email;
            $share->company = $request->company;
            $share->application = $request->application;
            $share->priority = $request->priority;
            $share->support_category = $request->support_category;
            $share->support_description = $request->support_description;
            $share->created_by = $request->created_by;
            $share->status = $request->status;
            $share->mime = $cover->getClientMimeType();
            $share->original_filename = $cover->getClientOriginalName();
            $share->filename = $cover->getFilename() . '.' . $extension;
        } else {
            $share = new Share();
            $share->support_ticket_no = $request->support_ticket_no;
            $share->contact_email = $request->contact_email;
            $share->company = $request->company;
            $share->application = $request->application;
            $share->priority = $request->priority;
            $share->support_category = $request->support_category;
            $share->support_description = $request->support_description;
            $share->created_by = $request->created_by;
            $share->status = $request->status;
        }
        $share->save();


        $contact_email = $share->contact_email = $request->get('contact_email');
        $email = $contact_email;
        $group_mail = ['humphreybrian43@gmail.com', 'muvictormo@gmail.com', 'harmfullbe@gmail.com', 'humphrey.ochieng@tamarix.co.ke'];
        $ticketno = $share->support_ticket_no = $request->get('support_ticket_no');
        $subject = "Support Request Ticket Number: $ticketno";
        $data['ticket_number'] = $ticketno;
        $priority =  $share->priority = $request->priority;
        if ($priority == 1) {
            Mail::send('emails.high', $data, function ($data) use ($email, $subject) {
                $data->to($email)->subject($subject);
            });
            Mail::send('emails.notifysupporth', $data, function ($data) use ($group_mail, $subject) {
                $data->to($group_mail)->subject($subject);
            });
        } elseif ($priority == 2) {
            Mail::send('emails.medium', $data, function ($data) use ($email, $subject) {
                $data->to($email)->subject($subject);
            });
            Mail::send('emails.notifysupportm', $data, function ($data) use ($group_mail, $subject) {
                $data->to($group_mail)->subject($subject);
            });
        } else {
            Mail::send('emails.low', $data, function ($data) use ($email, $subject) {
                $data->to($email)->subject($subject);
            });
            Mail::send('emails.notifysupportl', $data, function ($data) use ($group_mail, $subject) {
                $data->to($group_mail)->subject($subject);
            });
        }
        return redirect('/')->withSuccessMessage('We have received your support request. Kindly check your email for confirmation');
        return $share;
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Share  $share
     * @return \Illuminate\Http\Response
     */
    public function show(Share $share)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Share  $share
     * @return \Illuminate\Http\Response
     */
    // public function edit($id)
    // {
    //     //
    //     if (session('success_message')) {
    //         Alert::success('Thank you', session('success_message'));
    //     }
    //     $share = Share::find($id);
    //     $count_new = Share::whereDate('created_at', Carbon::today())->where('status', 0)->count();
    //     $new_tickets = Share::whereDate('created_at', Carbon::today())->where('status', 0)->get();
    //     return view('request.edit', compact('share', 'count_new', 'new_tickets'));
    // }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Share  $share
     * @return \Illuminate\Http\Response
     */
    // public function update(Request $request, $id)
    // {
    //     //
    //     $request->validate([
    //         'status' => 'required|integer',
    //         'solution_status' => 'required',
    //     ]);

    //     $share = Share::find($id);
    //     $share->support_ticket_no = $request->get('support_ticket_no');
    //     $share->contact_email = $request->get('contact_email');
    //     $share->support_category = $request->get('support_category');
    //     $share->support_description = $request->get('support_description');
    //     $share->status = $request->get('status');
    //     $share->solution_status = $request->get('solution_status');
    //     $share->resolved_by = $request->get('resolved_by');
    //     $share->man_hours = $request->get('man_hours');
    //     $share->save();
    //     $ticketno = $share->support_ticket_no = $request->get('support_ticket_no');
    //     $problem_description = $share->support_description = $request->get('support_description');
    //     $support_description = $share->solution_status = $request->get('solution_status');
    //     $contact_email = $share->contact_email = $request->get('contact_email');
    //     $data['title'] = "This is Test Mail Tuts Make";
    //     $data['ticket_number'] = $ticketno;
    //     $data['problem'] = $problem_description;
    //     $data['support_description'] = $support_description;
    //     $subject = "Solution for Ticket Number: $ticketno";

resources/views/request/create.blade.php
@extends('layouts.master')

@section('content')
<!--Start of Tawk.to Script-->
<script type="text/javascript">
    var Tawk_API = Tawk_API || {},
        Tawk_LoadStart = new Date();
    (function() {
        var s1 = document.createElement("script"),
            s0 = document.getElementsByTagName("script")[0];
        s1.async = true;
        s1.src = 'https://embed.tawk.to/5d146a6536eab97211197632/default';
        s1.charset = 'UTF-8';
        s1.setAttribute('crossorigin', '*');
        s0.parentNode.insertBefore(s1, s0);
    })();
</script>

<!--End of Tawk.to Script-->
<!-- <script src="//code.jivosite.com/widget/aykLjIgIRq" async></script> -->
<main id="main-container">
    <div class="content">
        <h2 class="content-heading">Create a Support Ticket</h2>
        <div class="row">
            <div class="col-md-12 col-lg-6">
                <div class="card">
                    <div class="card-header">Create a Support Request</div>
                    <div class="card-body">
                        <form method="post" action="{{ route('request.store') }}" enctype='multipart/form-data'>
                            @csrf
                            <div class="form-group">
                                <label for="inputAddress" class="col-form-label">Support Ticket Number</label>
                                <input type="text" readonly value="<?php echo date("Ymdhms"); ?>" class="form-control" id="support_ticket_no" name="support_ticket_no" placeholder="1234 Main St">
                            </div>
                            <div class="form-group">
                                <label for="inputAddress2" class="col-form-label">Select Company</label>
                                <select id="inputState" class="form-control" name="company" required>
                                    <option value="">Choose Company</option>
                                    @foreach($project as $p)
                                    <option value="{{$p->company}}">{{$p->company}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="inputAddress2" class="col-form-label">Select Application/Project</label>
                                <select id="inputState" class="form-control" name="application" required>
                                    <option value="">Choose Application/Project</option>
                                    @foreach($project as $p)
                                    <option value="{{$p->application}}">{{$p->application}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="inputAddress2" class="col-form-label">Service Priority</label>
                                <select id="inputState" class="form-control" name="priority" required>
                                    <option value="">Choose Priority</option>
                                    <option value="1">High (System Completely Unavailable | Response: < 2 Hours)</option> <option value="2">Medium (Critical System Functionality Unavailable | Response: 2-6 Hours)</option>
                                    <option value="3">Low (General System Issue | Response: < 24 Hours)</option> </select> </div> <div class="form-group">
                                            <label for="inputAddress2" class="col-form-label">Ticket Created by</label>
                                            <input type="text" required class="form-control" id="inputAddress2" name="created_by" placeholder="Enter Your Name">
                            </div>
                            <div class="form-group">
                                <label for="inputAddress" class="col-form-label">Contact Email</label>
                                <input type="email" required class="form-control" id="inputAddress" name="contact_email" placeholder="Enter Your Email Address">
                            </div>
                            <div class="form-group">
                                <label for="inputAddress2" class="col-form-label">Support Request Title</label>
                                <input type="text" required class="form-control" id="inputAddress2" name="support_category" placeholder="Support Request Title/ Title of Issue">
                            </div>
                            <div class="form-group">
                                <label for="inputAddress2" class="col-form-label">Attach File <i>(Max upload file size 4MB)</i></label>
                                <input type="file" class="form-control" id="inputAddress2" name="bookcover" placeholder="Attach File (Files max 5Mb)">
                            </div>
                            <div class="form-group">
                                <label for="inputAddress2" class="col-form-label">Support Request Description (Max charactrs: 500)</label>
                                <textarea class="form-control" name="support_description" rows=11 cols=50 maxlength=500 required></textarea>
                            </div>

                            <div class="form-group">
                                <input type="text" value="0" readonly class="form-control" hidden id="inputAddress2" name="status" placeholder="Apartment, studio, or floor">
                            </div>
                            <button type="submit" class="btn btn-primary">Submit Request</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        @include('sweetalert::alert')
    </div>
</main>

@endsection

resources/views/request/edit.blade.php
@extends('layouts.master')

@section('content')
<main id="main-container">
    <div class="content">
        <h6>Support Ticket: &nbsp; {{ $share->support_ticket_no }}</h6>
        <h6>Company: &nbsp; {{ $share->company}}</h6>
        @if($share->priority == 1)
        <h6>Priority: &nbsp; HIGH</h6>
        @elseif($share->priority == 2)
        <h6>Priority: &nbsp; MEDIUM</h6>
        @elseif($share->priority == 3)
        <h6>Priority: &nbsp; LOW</h6>
        @endif

        <div class="row">
            <div class="col-md-12 col-lg-6">

                <!-- Form row -->
                <div class="card">
                    @if($share->priority == 1)
                    <div class="card-header bg-danger">Support Ticket for {{ $share->company}}, created by {{ $share->created_by }}, {{ (new Carbon\Carbon($share->created_at))->diffForHumans() }}</div>
                    @elseif($share->priority == 2)
                    <div class="card-header bg-warning">Support Ticket for {{ $share->company}}, created by {{ $share->created_by }}, {{ (new Carbon\Carbon($share->created_at))->diffForHumans() }}</div>
                    @elseif($share->priority == 3)
                    <div class="card-header bg-primary">Support Ticket for {{ $share->company}}, created by {{ $share->created_by }}, {{ (new Carbon\Carbon($share->created_at))->diffForHumans() }}</div>

                    @endif
                    <div class="card-body">

                        <!--
						The .form-group class is the easiest way to add some structure to forms. Its only purpose is to provide margin-bottom around a label and control pairing. As a bonus, since it's a class you can use it with <fieldset>s, <div>s, or nearly any other element.
						You may also swap .row for .form-row, a variation of our standard grid row that overrides the default column gutters for tighter and more compact layouts.
						-->
                        <form method="POST" action="{{ route('shares.update', $share->id) }}">
                            @method('PATCH')
                            @csrf

                            <div class="form-group">
                                <label for="inputAddress" class="col-form-label">Support Ticket Number</label>
                                <input type="text" readonly value="{{ $share->support_ticket_no }}" class="form-control" id="support_ticket_no" name="support_ticket_no" placeholder="1234 Main St">
                            </div>
                            <div class="form-group">
                                <label for="inputAddress" class="col-form-label">Contact Email</label>
                                <input type="email" readonly class="form-control" value="{{ $share->contact_email }}" id="inputAddress" name="contact_email" placeholder="1234 Main St">
                            </div>
                            <div class="form-group">
                                <label for="inputAddress2" class="col-form-label">Application</label>
                                <input type="text" readonly class="form-control" id="inputAddress2" value="{{ $share->application }}" name="application" placeholder="Application">
                            </div>
                            <div class="form-group">
                                <label for="inputAddress2" class="col-form-label">Support Request Title</label>
                                <input type="text" readonly class="form-control" id="inputAddress2" value="{{ $share->support_category }}" name="support_category" placeholder="Support Category">
                            </div>
                            <div class="form-group">
                                <label for="inputAddress2" class="col-form-label">Support Issue Description</label>
                                <textarea id="story" readonly class="form-control" name="support_description" rows="5" cols="33" placeholder="Support Description">
                                {{ $share->support_description }}
                                </textarea>
                            </div>
                            <div class="form-group">
                                <label for="man_hours" class="col-form-label">Man Hours(Hours taken to work on ticket)</label>
                                <input type="number" class="form-control" id="man_hours" value="{{ $share->support_category }}" name="man_hours" placeholder="Man Hours">
                            </div>
                            <div class="form-group">
                                <label for="inputAddress2" class="col-form-label">Solution Description</label>
                                <textarea id="story" class="form-control" name="solution_status" rows="5" cols="33" placeholder="Support Description">
                                {{ $share->solution_status }}
                                </textarea>
                            </div>
                            <div class="form-group">
                                <input type="text" value="1" readonly class="form-control" hidden id="inputAddress2" name="status" placeholder="Apartment, studio, or floor">
                            </div>
                            <div class="form-group">
                                <input type="text" value="{{Auth::user()->email}}" readonly class="form-control" hidden id="inputAddress2" name="resolved_by" placeholder="Apartment, studio, or floor">
                            </div>
                            @if($share-> status == 1)
                            This Ticket has Already been Responded to
                            @else($share-> status == 0)
                            <button type="submit" class="resolve btn btn-primary">Respond to Service Ticket</button>
                            @endif

                            <a href="{{url('/')}}" class="btn btn-primary">Go Back</a>
                        </form>
                        <script>
                            $(".resolve").on("submit", function() {
                                return confirm("Do you want to delete this item?");
                            });
                        </script>

                    </div><!-- .card-body -->
                </div><!-- .card -->
                <!-- /End Form row -->

            </div><!-- .col -->

            <div class="col-md-12 col-lg-6">
                <div class="card">
                    @if($share->filename !== null)
                    <div class="card-header">Attachment <a href="{{url('uploads/'.$share->filename)}}" target="_blank"><button class="resolve btn btn-primary">Download attachment</button></a></div>
                    @else
                    <div class="card-header">No Attachment Available</div>
                    @endif
                    <div class="card-body">
                        <!-- Content here-->

                        @if($share->filename !== null)
                        <img class="card-img-top" src="{{url('/uploads/'.$share->filename)}}" alt="{{$share->filename}}">
                        @else
                        <h3>Attachment not available</h3>
                        @endif





                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

@endsection