routes/web.php
<?php



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/welcome', function () {
//     return view('welcome');
// });


// Auth::routes();
Auth::routes([
    'verify' => true,
    'register' => false,
    ]);

Route::resource('/', 'RequestController');
Route::resource('request', 'RequestController');

Route::resource('shares', 'ShareController');



// Route::resource('requests', 'SupportRequestController');
// Route::get('requests', 'SupportRequestController@getGuzzleRequest');


Route::resource('welcome', 'ShareController@getGuzzleRequest');

//Add clients
Route::resource('client', 'ClientController');
//manage users
Route::resource('manage_users', 'UserManagerController');
///
Route::resource('books', 'BookController');
//Man Hours
Route::resource('man_hours',  'ManhourController');

//change passsword routes
Route::get('change-password', 'ChangePasswordController@index');
Route::post('change-password', 'ChangePasswordController@store')->name('change.password');

app/Client.php
<?php

namespace App;

use Illuminate\Contracts\Auth\Guard;
use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    //
    protected $guarded = [];
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use App\Share;
use Illuminate\Support\Carbon;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware(['auth', 'verified']);
    }
    public function index()
    {
        //
        if (session('success_message')) {
            Alert::success('Thank you', session('success_message'));
        }
        $requests = Share::orderBy('status')->get();

        $clients = Client::all();
        //These go to Client View
        $project = Client::all();
        $count_project = Client::count();
        $count_companies = Client::count();
        $count_project_complete = Client::whereNotNull('date_ended')->count();
        $count_project_incomplete = Client::whereNull('date_ended')->count();
        //ENd of client view

        // $checkins = Checkin::whereDate('created_at', Carbon::today())->get();
        return view('client.index', compact('clients','count_project_complete', 'count_project_incomplete', 'count_project', 'count_companies'));
        // return view ('client.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view ('client.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'company' => 'required',
            'application' => 'required',
            'date_started' => 'required',
            
        ]);

        $client = new Client([

            'company' => $request->get('company'),
            'application' => $request->get('application'),
            'date_started' => $request->get('date_started'),
            'date_ended' => $request->get('date_ended'),
        ]);
        $client->save();
        return redirect('/client')->withSuccessMessage('You have Successfully submitted the Project Details.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function show(Client $client)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Client $client)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function destroy(Client $client)
    {
        //
    }
}

resources/views/client/create.blade.php
@extends('layouts.master')
@section('content')
<main id="main-container">
    <div class="content">


        <div class="row">
            <div class="col-md-12 col-lg-6">

                <!-- Form row -->
                <div class="card">
                    <div class="card-header">Create company and Application Record</div>
                    <div class="card-body">

                        <!--
						The .form-group class is the easiest way to add some structure to forms. Its only purpose is to provide margin-bottom around a label and control pairing. As a bonus, since it's a class you can use it with <fieldset>s, <div>s, or nearly any other element.
						You may also swap .row for .form-row, a variation of our standard grid row that overrides the default column gutters for tighter and more compact layouts.
						-->
                        <form method="post" action="{{ route('client.store') }}">
                            @csrf

                            <div class="form-group">
                                <label for="inputAddress2" class="col-form-label">Company</label>
                                <input type="text" class="form-control" id="company" name="company" placeholder="Company">
                            </div>
                            <div class="form-group">
                                <label for="inputAddress" class="col-form-label">Project</label>
                                <input type="text" class="form-control" id="application" name="application" placeholder="Project">
                            </div>
                            <div class="form-group">
                                <label for="inputAddress2" class="col-form-label">Project Start Date</label>
                                <input type="date" class="form-control" id="date_started" name="date_started" placeholder="Date Sarted">
                            </div>
                            <div class="form-group">
                                <label for="inputAddress2" class="col-form-label">Project End Date</label>
                                <input type="date" class="form-control" id="date_ended" name="date_ended" placeholder="Date Ended">
                            </div>


                            <div class="form-group">
                                <!-- <label for="inputAddress2" class="col-form-label">status</label> -->
                                <input type="text" value="0" readonly class="form-control" hidden id="inputAddress2" name="status" placeholder="Apartment, studio, or floor">
                            </div>
                            <button type="submit" class="btn btn-primary">Submit Request</button>
                        </form>

                    </div><!-- .card-body -->
                </div><!-- .card -->
                <!-- /End Form row -->

            </div><!-- .col -->


        </div><!-- .row -->



        @include('sweetalert::alert')
    </div><!-- .content -->
</main>
@stop

resources/views/client/index.blade.php
@extends('layouts.master')
@section('content')
<main id="main-container">
    <div class="content">

        @auth
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6">

                <!-- Item sold -->
                <div class="card stats-card">
                    <div class="stats-icon bg-success">
                        <span class="ti-bag"></span>
                    </div>
                    <div class="stats-ctn">
                        <div class="stats-counter"><span class="counter">{{$count_companies}}</span></div>
                        <span class="desc">Companies</span>
                    </div>
                </div><!-- .card -->
                <!-- /End Item sold -->

            </div><!-- .col -->
            <div class="col-lg-3 col-md-6 col-sm-6">

                <!-- Earnings -->
                <div class="card stats-card">
                    <div class="stats-icon bg-danger">
                        <span class="ti-wallet"></span>
                    </div>
                    <div class="stats-ctn">
                        <div class="stats-counter"><span class="counter">{{$count_project}}</span></div>
                        <span class="desc">Total Applications</span>
                    </div>
                </div><!-- .card -->
                <!-- /End Earnings -->

            </div><!-- .col -->
            <div class="col-lg-3 col-md-6 col-sm-6">

                <!-- Messages -->
                <div class="card stats-card">
                    <div class="stats-icon bg-info">
                        <span class="ti-email"></span>
                    </div>
                    <div class="stats-ctn">
                        <div class="stats-counter"><span class="counter">{{$count_project_complete}}</span></div>
                        <span class="desc">Complete Applications</span>
                    </div>
                </div><!-- .card -->
                <!-- /End Messages -->

            </div><!-- .col -->
            <div class="col-lg-3 col-md-6 col-sm-6">

                <!-- Notifications -->
                <div class="card stats-card">
                    <div class="stats-icon bg-secondary">
                        <span class="ti-save"></span>
                    </div>
                    <div class="stats-ctn">
                        <div class="stats-counter"><span class="counter">{{$count_project_incomplete}}</span></div>
                        <span class="desc">Incomplete Applications</span>
                    </div>
                </div><!-- .card -->
                <!-- /End Notifications -->

            </div><!-- .col -->
        </div><!-- .row -->
        <div class="row">
            <div class="col-12">

                <!-- Invoice -->
                <div class="card">
                    <div class="card-body">
                        <div class="card-header-inside">
                            Service Tickets
                        </div>

                        <table id="mytable" class="table table-striped table-responsive">
                            <thead>
                                <tr>
                                    <th>Company</th>
                                    <th>Application</th>
                                    <th>Date Started</th>
                                    <th>Date Ended</th>
                                </tr>
                            </thead>
                            <tbody>



                                @foreach($clients as $client)
                                <tr>
                                    <td>{{ $client->company }}</td>
                                    <td>{{ $client->application }}</td>
                                    <td>{{ \Carbon\Carbon::parse($client->date_started)->format('d/M/Y')}}</td>
                                    <td>{{ \Carbon\Carbon::parse($client->date_ended)->format('d/M/Y')}}</td>
                                </tr>
                                @endforeach


                            </tbody>
                        </table>

                    </div><!-- .card-body -->
                </div><!-- .card -->
                <!-- /End Invoice -->


            </div><!-- .col -->
        </div><!-- .row -->
        @else

        @endauth


        @include('sweetalert::alert')
    </div><!-- .content -->
</main>
@stop